global.words = [
	{ word: "mobil", clue: "Kendaraan" },
	{ word: "motor", clue: "Kendaraan" },
	{ word: "sepeda", clue: "Kendaraan" },
	{ word: "pesawat", clue: "Transportasi" },
	{ word: "kereta", clue: "Transportasi" },
	{ word: "kapal", clue: "Transportasi" },
	{ word: "ojek", clue: "Transportasi" },
	{ word: "jakarta", clue: "Kota" },
	{ word: "bandung", clue: "Kota" },
	{ word: "surabaya", clue: "Kota" },
	{ word: "madura", clue: "Kota" },
	{ word: "balikpapan", clue: "Kota" },
	{ word: "indonesia", clue: "Negara" },
	{ word: "jepang", clue: "Negara" },
	{ word: "belanda", clue: "Negara" },
	{ word: "jawa", clue: "Pulau" },
	{ word: "bali", clue: "Pulau" },
	{ word: "sulawesi", clue: "Pulau" },
	{ word: "kalimantan", clue: "Pulau" },
	{ word: "papua", clue: "Pulau" },
	{ word: "sumatera", clue: "Pulau" },
	{ word: "borobudur", clue: "Candi" },
	{ word: "prambanan", clue: "Candi" },
];